# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Ambro Ventures
# Description of the Site
description: our journey has only just begun
# URL of Image of the Site
site-image: 
# Keywords of the Site
site-keywords: 
# URL for the Image of custom Favicon
favicon-url: https://raw.githubusercontent.com/AmbroVentures/AmbroVentures.github.io/main/assets/images/logo.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://tse1.mm.bing.net/th/id/OIG.bsVxr3_2Gk2WslQWbFTB?w=1024&h=1024&rs=1&pid=ImgDetMain

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: hello@ambro.ventures
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: 
github_username:  AmbroVentures
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: /

# Name of the Author
author-name: AmbroVentures
# URL for the Image of the Author
author-image: https://raw.githubusercontent.com/AmbroVentures/AmbroVentures.github.io/main/assets/images/logo.png
# https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png #incognito
# 60 Words About the Author
author-about: A few hobby projects developed with passion by friends & family. Follow us on this creative and innovative adventure.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/AmbroVentures

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
